# Custom Grazie configuration

extends: existence

# Set warning message for possible spelling mistakes
message: "Possible spelling mistake: '%s'"

# Set warning level to 'warning'
level: warning

# Set scope of files to check for spelling mistakes
scope: .cpp, .cc, .cxx, .hpp, .hxx

# Specify words to be checked for spelling mistakes
tokens:
  - alloc
  - buffer
  - initialize
  - length
  - method
  - receive
  - release
  - succeed
  - switch
  - with
  - static_cast

# Ignored words and phrases
ignore:
  - "lorem ipsum"
  - "ipso facto"


# Grammar and style rules
rules:
  Cpp:
    - enable: true
      style: google

# Enabled checks
checks:
  grammar:
    uselessWords: true
    unnecessaryPassiveVoice: true
    wordiness: true
    redundancy: true

  spelling:
    typos: true
    mixedCase: true
    camelCase: true
    abbreviations: true
    numbers: true
    urls: true
    emails: true

  naming:
    functionNames:
      style: google
      except:
        - 'SetUp'
        - 'TearDown'

    variableNames:
      style: google
      except:
        - 'tmp'
        - 'i'
        - 'j'
        - 'k'

    classNames:
      style: google

    enumNames:
      style: google

    namespaceNames:
      style: google

    structNames:
      style: google

    memberVariableNames:
      style: google
      except:
        - 'tmp'
        - 'm_.*'

    constantNames:
      style: google